### ISSUE TITLE
[Question] Can I create and manage mailing lists using freepost.io ?

### ISSUE THREAD

**Issue by hiveship** [kaiyou/freeposte.io#12]
I am wondering if freeposte.io can create and manage mailing lists ?

If it's not possible yet, I may help to develop this feature :)

**Comment by kaiyou** [comment]
It does not manage mailman or Sympa-like mailing lists for now. It does however manage aliases with multiple destinations (which are named "distribution lists" in Zimbra).

You are more than welcome to add mailing lists support. How do you imagine interfacing a mailing lists server with the current admin dashboard ? Would the lists service be isolated and managed separately?

**Comment by hiveship** [comment]
Distribution list is exactly what I need ! 
But... I don't really understand the difference between "mailing list" and "distribution list" then ?

**Comment by kaiyou** [comment]
Distribution list is basically an alias: any mail sent to the address is forwarded to one or more destination addresses.

A mailing list has the same features, plus subscription from users, archives, daily deliveries, moderation, etc.

The former are useful for small-scale webservers where a functional alias (admin@, etc.) is forwarded to the proper receipients. The latter is interesting when managing a large community of autonomous users around the Internet that use e-mail for managing discussion threads.
