### ISSUE TITLE
Clamav error

### ISSUE THREAD

**Issue by abnerjacobsen** [kaiyou/freeposte.io#18]
Hi,

I got Freeposte up and running but the antivirus docker has this error's:

LibClamAV Warning: Cannot dlopen libclamunrar_iface: file not found - unrar support unavailable
LibClamAV Error: cli_loaddbdir(): No supported database files found in /data
ERROR: Can't open file or directory

How I can solve this ?

Regards,

**Comment by kaiyou** [comment]
Thanks for reporting, indeed ``freshclam`` was not running anymore on the antivirus server, which prevented it from initializing the database and running any further update.

This should be fixed by now, both on master and ``1.0`` branch.

**Comment by kaiyou** [comment]
I just tested on fresh server, the problem seems to be fixed.
