### ISSUE TITLE
Dovecot can't be created due to ABI (2.24 -> 2.25)

### ISSUE THREAD

**Issue by pheonyx** [kaiyou/freeposte.io#32]
First, thank's for your great work.
I want to find an open alternative of *poste.io* and I found your project.

But I've a problem with the imap container (Dovecot):
```
Aug 02 19:52:32 imap(*******@******): Error: Couldn't load required plugin /usr/lib/dovecot/lib90_antispam_plugin.so: Module is for different ABI version 2.2.ABIv24(2.2.24) (we have 2.2.ABIv25(2.2.25))
Aug 02 19:52:32 imap(*******@******): Error: Internal error occurred. Refer to server log for more information.
```
So, I've this message every time I try to access to Roundcube (and I've got this message with Roundcube: **Connection to storage server failed.**)

How could I repair that ?

Best regards,

**Comment by kaiyou** [comment]
Thanks for reporting, I haven't yet tested yesterday's builds. This is probably related to the antispam plugin currently being installed from a shipped binary. I will rebuild the shipped binary and push it to all branches.

**Comment by kaiyou** [comment]
I just created #33 to get rid of this kind of issues for good before next time. Still build the new APKs.

**Comment by pheonyx** [comment]
Thank's

**Comment by kaiyou** [comment]
I am reopening this as this is not fixed and will probably affect other users.

**Comment by pheonyx** [comment]
Sorry, I had no thought.

**Comment by kaiyou** [comment]
I pushed commit e471a25 to fix this. Builds just finished on Docker Hub, could you try again?

**Comment by jkarlosb** [comment]
Hi, I noticed next error:

```Error: Couldn't load required plugin /usr/lib/dovecot/lib90_antispam_plugin.so: Module is for different ABI version 2.2.ABIv25(2.2.25) (we have 2.2.ABIv24(2.2.24))
````

I pulled and recreated all containers but It not working, do you know what can I do?

**Comment by kaiyou** [comment]
Did you pull containers from Docker Hub or build them from the ``docker-config.yml`` file? If the latter, disable the cache when building, otherwise cached intermediary containers with old versions of Dovecot will be used for the build.

**Comment by jkarlosb** [comment]
I build the containers from my docker-compose.yml modified (I am tested on a t2.micro instance and I can't run clamav because I only have 1GB Ram), I always do this and it works fine. 

Then I pulled the repo, and I tried with this commands but it not works:

`docker-compose up -d --force-recreate`
`docker-compose up -d --build`

I just do this:

```
docker-compose down --rmi all
docker-compose build --no-cache

....

Building milter
Step 1 : FROM alpine:edge
 ---> 3fc33d6d5e74
Step 2 : RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories  && apk add --update      rmilter@testing rsyslog  && rm -rf /var/cache/apk/*
 ---> Running in ce9d6640448e
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libfastjson.so.3 (missing):
    required by:
                 rsyslog-8.20.0-r0[so:libfastjson.so.3]
ERROR: Service 'milter' failed to build: The command '/bin/sh -c echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories  && apk add --update      rmilter@testing rsyslog  && rm -rf /var/cache/apk/*' returned a non-zero code: 2
```

I just try it in to another host and I find the same error, I can´t up the containers now.

**Comment by kaiyou** [comment]
Okay, I have the same error here.
The dependency costraint sounds like a bug upstream in Alpine, I will check again tonight and try to ping them on IRC.

**Comment by kaiyou** [comment]
```
<kaiyou> Hey everyone, I have a dependency problem on edge, which I know happens from time to time, but do you know how long it usually takes to solve (cannot install rsyslog)
<kaiyou> Details: rsyslog requires so:libfastjson.so.3 but libfastjson now ships libfastjson.so.4 I believe
<hrw> kaiyou: so rsyslog needs bump and rebuild
* hrw hides
```

I will try and push something to patchwork to get the rsyslog package bumped.

**Comment by kaiyou** [comment]
Just had a discussion with ncopa, this should be fixed soon:

```
<ncopa> kaiyou_: i pushed rsyslog rebuild
```

**Comment by jkarlosb** [comment]
It works perfectly now. Rmilter is built without errors through `docker-compose build --no-cache`

Thanks

**Comment by kaiyou** [comment]
And Dockerhub successfully built a minute ago. Closing this issue, thanks again.
