### ISSUE TITLE
Postfix configuration broken

### ISSUE THREAD

**Issue by XYunknown** [kaiyou/freeposte.io#46]
In it's current state the postfix config fails with the message:
postfix/master[28]: fatal: relayhost parameter setting must not contain multiple values: {{ RELAYHOST }}

**Comment by kaiyou** [comment]
Did you update your environment file? We should find a proper way ot introduce new configuration values.

**Comment by XYunknown** [comment]
I added the RELAYHOST= parameter, but left the value empty. Which is the correct value to omit the field?

**Comment by kaiyou** [comment]
Having the value empty should work, I just tested it yesterday. I am having trouble with local Docker daemon but I will try again asap.

**Comment by XYunknown** [comment]
Apparently I was missing the override mount in the docker-compose file. How does this contribute to the RELAYHOST parameter not being commented out?

**Comment by kaiyou** [comment]
It should not have. But maybe adding the mount forced your Docker Compose to recreate the container, which modifying the env file did not?

**Comment by XYunknown** [comment]
Propably, that is likely. Thanks for the fast help, and sry that I wasn't able to merge the BetterCrypto config before you already did :) Good job btw.
