### ISSUE TITLE
Public demo/tests server

### ISSUE THREAD

**Issue by kaiyou** [kaiyou/freeposte.io#48]
I am currently setting up a demo/tests server with public access. Any suggestions on how-to manage the machine?

My main questions for now:

- how often should I reset the data?
- how should I reset the data (some imutable filesystem?)
- where should I publish the public accounts if any?
- how could I prevent repeated vandalism?

**Comment by kaiyou** [comment]
A basic server is running at https://test.freeposte.io, still have to figure out how to reset the data properly and where I should publish default accounts credentials.

**Comment by kaiyou** [comment]
I also just set up centurylink/watchtower to that containers are automatically updated to the latest ``testing`` build.

**Comment by kaiyou** [comment]
I just wrote a Wiki page to publish the first information about the demo server : https://github.com/kaiyou/freeposte.io/wiki/Demo-server

**Comment by acs-ferreira** [comment]
@kaiyou demos are not working
