### ISSUE TITLE
Remove sensitive information

### ISSUE THREAD

**Issue by d-fens** [kaiyou/freeposte.io#52]
In docker for postfix apk add postfix-pcre

In the following conf /etc/postfix/master.cf for submission add:
  -o cleanup_service_name=authclean
authclean unix  n       -       n       -       0       cleanup
  -o header_checks=pcre:/etc/postfix/outgoing_mail_header_filters

Add /etc/postfix/outgoing_mail_header_filters for postmap using something similar to:
https://raw.githubusercontent.com/mail-in-a-box/mailinabox/master/conf/postfix_outgoing_mail_header_filters

**Comment by kaiyou** [comment]
The mailinabox configuration sounds fine, we should be careful and enable the cleaning service for both submission and smtps.

Feel free to pull request if you have some time to implement this, I probably implement it in a couple of days.
