### ISSUE TITLE
Database initialization error at first start

### ISSUE THREAD

**Issue by e29qwg** [kaiyou/freeposte.io#53]
After running ```docker-compose up -d```, I just executed a ```manage.py``` to create an administrator account and I found it always unexpectedly shows up warnings (as of below). I am able to successfully logged in. However, I could not access the Manage Domains page in admin console.

```
# docker exec -it freeposte_admin_1 python manage.py admin admin example.net admin

/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute domain_name from non-mapped class Email
  (desc.fget.__name__, cls.__name__))
/usr/local/lib/python3.5/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute email from non-mapped class Email
  (desc.fget.__name__, cls.__name__))
```

After a while investigation, I found that there is an error upgrading from initial database schema. 
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a NOT NULL column with default value NULL [SQL: 'ALTER TABLE alias ADD COLUMN wildcard BOOLEAN NOT NULL']
```

Hope that might contribute to this project.

**Comment by kaiyou** [comment]
This is weird indeed, it is definitively related to the ``add_table`` operation in migration ``c5696b48442d``.

However the default value is explicitely mentionned in the migration script. I will check the Alembic syntax maybe. In the meantime you should be able to run ``ALTER TABLE alias ADD COLUMN wildcard BOOLEAN NOT NULL DEFAULT 0`` on your SQLite database.

**Comment by kaiyou** [comment]
The bug is now fixed, I was not using the proper attribute for default values in the Alembic script. If you did alter your database manually, either you do not have any data and are willing to drop your database and restart Freeposte.io to rebuild it from scratch, or you could update the Alembic revision:

```
UPDATE alembic_version SET version_num='c5696b48442d';
```

After restarting Freeposte, you should see a last migration (default spam threshold) running.
