### ISSUE TITLE
spam not moved to junk folder

### ISSUE THREAD

**Issue by diresi** [kaiyou/freeposte.io#71]
Hi,

I'm running the `latest` images as of yesterday (probably 79adbbb).
I've enabled spam detection in the admin console, and spam is actually detected and marked by rspamd, headers are inserted like:
```
X-Spamd-Result: default: True [24.36 / 15.00]
 RBL_SPAMHAUS_XBL(4.00)[]
 RBL_SPAMHAUS_XBL_ANY(4.00)[]
 HFILTER_HOSTNAME_UNKNOWN(2.50)[]
 BAYES_SPAM(3.06)[92.67%]
 HFILTER_HELO_BAREIP(3.00)[]
 RBL_SORBS_RECENT(1.50)[]
 RBL_SPAMHAUS_CSS(2.00)[]
 RBL_MAILSPIKE_WORST(2.00)[]
 MIME_UNKNOWN(0.10)[application/x-rar-compressed]
 RBL_SORBS(0.00)[]
 R_SPF_NEUTRAL(0.00)[?all]
 ONCE_RECEIVED(0.10)[]
 RBL_UCEPROTECT_LEVEL1(1.00)[]
 MIME_HTML_ONLY(0.20)[]
 RBL_SEM(1.00)[]
 MIME_GOOD(-0.10)[multipart/mixed]
X-Rspamd-Server: antispam
X-Rspamd-Scan-Time: 0.37
X-Rspamd-Queue-ID: D24918003EE
X-Spam: yes
```

Still those messages are kept in my INBOX and not moved to Junk or marked as read.
It seems to me, that the dovecot sieve scripts are outdated or targeted at some other spamfilter (`X-Spam-Status`, spamassassin?) and not effective anymore.

How do I achieve the same result (automatically move spam to junk and mark it read) with the current images?

Thanks,
Christoph

**Comment by kaiyou** [comment]
Thanks for reporting this, it seems indeed that the latest Rspamd version does not add the ``X-Spam-Status`` header. We should spend some time matching the ``X-Spamd-Result`` header, which was a hassle some time ago unfortunately.

**Comment by diresi** [comment]
Maybe I can find some time to help out here. For starters, I'll try to figure out how to debug sieve scripts ;).

**Comment by kaiyou** [comment]
Debugging sieve scripts is painful. You can start by enabling ``mail_debug`` in Dovecot. Thanks for your help!

**Comment by diresi** [comment]
I've come up with a PR, what do you think about it?
