### ISSUE TITLE
Problem with send and delivery with `latest`

### ISSUE THREAD

**Issue by aminb** [kaiyou/freeposte.io#76]
I just noticed that sending and receiving email on master is broken. The latest version I tested with is the one with my max message size commit as its last commit.

Roundcube just gives a `SMTP Error (-1): Connection to server failed.` dialog when trying to send an email. And for receiving, looks like there's a socket error and server doesn't accept connection requests.

I haven't yet pinpointed the source of problem though.

**Comment by kaiyou** [comment]
The test server has been running with no specific issues and I run tests locally pretty much every day, it doesn't seem like receiving or sending emails is completely broken to me. Could you provide some more details, like Docker logs around the time you try and send these emails?

**Comment by aminb** [comment]
Oh, a noob mistake on my part:

In my pull request, I had extraneous spaces: `MESSAGE_SIZE_LIMIT = 50000000`, completely forgetting that bash doesn't like whitespaces around `=` and the variable wasn't assigned to. And so postfix wasn't starting correctly.

I just realized you fixed it in 883afb3.

Pulling the latest `latest` fixed everything.

Thanks!
